### ISSUE TITLE
Fix Icon Warning for iPad

### ISSUE THREAD

**Issue by kmcurry** [popcatalin118/3scape_iOS#1]
/Users/kmcurry/Agrica/3Scape/code/3scape_iOS/3Scape_App/Images.xcassets: A 76x76 app icon is required for iPad apps targeting iOS 7.0 and later

![screen shot 2015-01-28 at 11 50 59 am](https://cloud.githubusercontent.com/assets/69151/5942354/f85abbf2-a6e4-11e4-8aa6-220965e9a54c.png)

**Comment by cdpop** [comment]
warnings should be gone
