### ISSUE TITLE
Send 'Log in' link directly to 3Scape.me login

### ISSUE THREAD

**Issue by kmcurry** [popcatalin118/3scape_iOS#3]
![img_0437](https://cloud.githubusercontent.com/assets/69151/5942477/dd464c40-a6e5-11e4-8880-426e2c99636b.PNG)
![img_0438](https://cloud.githubusercontent.com/assets/69151/5942479/e0edcb3e-a6e5-11e4-8d1a-89dd6ab52d57.PNG)
![img_0439](https://cloud.githubusercontent.com/assets/69151/5942480/e2be7eea-a6e5-11e4-9f0a-a4257f25568f.PNG)

**Comment by cdpop** [comment]
would you like for me to get rid of the sign up page as well?

**Comment by kmcurry** [comment]
Yes, thank you.

**Comment by cdpop** [comment]
both log in and sign up should be fixed

**Comment by kmcurry** [comment]
Cool I'll check it out

On Thursday, January 29, 2015, popcatalin118 notifications@github.com
wrote:

> both log in and sign up should be fixed
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kmcurry/3scape_iOS/issues/3#issuecomment-72063069.

## 

Kevin Curry
Virginia Beach, VA

3Scape begins @ http://3Scape.me

**Comment by kmcurry** [comment]
There isn't any pull request for an update.

I also noticed we need to add a .gitignore and list some things in there like .DS_Store we don't want to version control

**Comment by kmcurry** [comment]
I just realized I need to open a qa branch on my repo
