### ISSUE TITLE
Why don't UI buttons work?

### ISSUE THREAD

**Issue by kmcurry** [popcatalin118/3scape_iOS#6]
When I click on the UI buttons nothing happens.

Note: we will change the UI for tablet and phone but we'll probably still need to know why our existing buttons don't work.

Priority is understanding what's wrong. Reply in comments. Fix if possible, secondary priority.

**Comment by cdpop** [comment]
Which button are you referring to? The display button under sign up was a test for me to ensure that I am grabbing the right information when a person tried to sign up

**Comment by kmcurry** [comment]
I mean on the /create page

On Wed, Jan 28, 2015 at 5:59 PM, popcatalin118 notifications@github.com
wrote:

> Which button are you referring to? The display button under sign up was a
> test for me to ensure that I am grabbing the right information when a
> person tried to sign up
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kmcurry/3scape_iOS/issues/6#issuecomment-71935066.

## 

Kevin Curry
Virginia Beach, VA

3Scape begins @ http://3Scape.me

**Comment by kmcurry** [comment]
![screen shot 2015-01-28 at 10 08 35 pm](https://cloud.githubusercontent.com/assets/69151/5951813/44bf5a7a-a73a-11e4-90a8-8f20e54f59d4.png)
![screen shot 2015-01-28 at 10 08 40 pm](https://cloud.githubusercontent.com/assets/69151/5951815/46c86f14-a73a-11e4-8ca8-d05c65142d29.png)

**Comment by cdpop** [comment]
i will look into that and get back to you tomorrow

**Comment by cdpop** [comment]
this is something we would need to look into the website code, because issue persists within safari and chrome browser

**Comment by kmcurry** [comment]
To summarize: device down is detected but not device up. (Device is likely assumed to be a mouse.) We'll track this as an issue in 3Scape.
